language: android

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

android:
  components:
    - tools
    - build-tools-25.0.3
    - android-25
    - platform-tools

    # Additional components
    - extra-android-m2repository
    - extra-google-m2repository

branches:
  only:
    - master
    - /^dev\d+\.\d+\.\d+$/

script: ./travis-build.sh
